[package]
name = "html-to-pulldown-cmark-events"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
ego-tree = "0.6.2"
pulldown-cmark = "0.9.2"
scraper = { version = "0.14.0", default-features = false }
